### ISSUE TITLE
Cheat general options file

### ISSUE THREAD

**Issue by c0m3tx** [darrikonn/cheat#2]
In readme, `~/.cheat.yaml` is indicated as the file read by the application for configuration purposes. I tried setting a custom text editor but it was ignored. 

Looks like it is looking for a different file `~/.cheet.yaml` in the code. 

In fact, it works using cheet instead of cheat. 

Which one is correct? Thanks!

**Comment by darrikonn** [comment]
Wow, that's a typo! It should definitely be `~/.cheat.yaml`.
I see that I did the same for `~/.cheatsheet.db`.

Will update in the next version. This will be breaking changes for existing users since the default database will be renamed. So I'll bump the major version to `1`. 

Thanks for reporting this!
I'll post a link to the PR when it's ready, before creating the new version!

**Comment by darrikonn** [comment]
Current users will have to rename their existing database to the new name, or set their old name in the config, when they upgrade to `v1.0.0`:
1. `mv ~/.cheetsheet.db ~/.cheatsheet.db`
or
2. add `database: "~/.cheetsheet.db"` in `cheat.yaml`.

**Comment by darrikonn** [comment]
This has been fixed in https://github.com/darrikonn/cheat/releases/tag/v1.0.0

You can upgrade with the package manager that suits your environment, or:
```bash
curl -s https://raw.githubusercontent.com/darrikonn/cheat/master/install.sh | bash -s -- -b /usr/local/bin
```

And then run:
```bash
mv ~/.cheetsheet.db ~/.cheatsheet.db
mv ~/.cheet.yaml ~/.cheat.yaml
```

Thanks again!

**Comment by c0m3tx** [comment]
Glad to help! :)
